Bump min SDK to 26 as required for adaptive icons
Addresses the following compilation error:

  packages/apps/Trebuchet/res/mipmap-anydpi/ic_launcher.xml: error: <adaptive-icon> elements require a sdk version of at least 26.

Change-Id: I587ecaa657cffc4a625e2905c237243bafe79e8e